# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'Etablissement")),
                ('ville', models.CharField(max_length=255, null=True, verbose_name='Ville')),
                ('quartier', models.CharField(max_length=255, verbose_name='Nom du Quartier')),
                ('repere', models.TextField(max_length=255, verbose_name='Répère')),
                ('telephone', models.CharField(max_length=30, verbose_name='Telephone(s)')),
                ('email', models.EmailField(max_length=255, verbose_name='Email(s)')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('latitude', models.CharField(max_length=255, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=255, verbose_name='Longitude')),
            ],
            options={
                'verbose_name_plural': 'Etablissements',
            },
        ),
    ]
